name: weellu_web
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1  
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  fl_chart: ^0.36.1
  provider: ^5.0.0
  data_table_2: ^2.0.3
  lint: any
  font_awesome_flutter: ^9.0.0
  flutter_feather_icons: ^2.0.0+1
  cloud_firestore: any
  google_sign_in: any
  firebase_storage: any
  firebase_auth: any
  firebase_core: any
  path_provider: any

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  uses-material-design: true

